language: python
dist: xenial
script: $PYTHON run.py
deploy:
  provider: releases
  edge: true
  token: "hGjNsMJY5OEy3BAobrPWdWyDKaa/Ngw34h3KQ3K4LVSjbPRvSM6SRXfsoKZuCZizHcihkcbK7Eb3hA0tMRywNVmt5ouxT/cSCLV16T+mv7lIqXtDRyi8p6uDJ4A5gW3xwCBBbsLXenlje22OmCZXKtM5qcP0PAak1uPk7QGhl3vFPR1PHAJbcsOVJ+rvbZ3sKL1au9KcNB+l3MJhM6L7X+JWn6X5tzeDW8DwX9Mwav27+HQPFGEJ3+VyY5F3Wa7ssEF4en83EhTPEtVoUwA06lN4ij4urEhCWuKpCwedUASFkEw7onGIp1K4m2jV6MpWYQJhEUFiDFBLHXS9dKFEmmVr7HbselxsjF6Zk+5qQ88Wwjapnhf0Tyx5Ac6JsVweHYI7P0NLwH6L2yP6oCWEyistUNBSrIScQ61GUWK1+5BWjIPI229CAAH/93/l5RGyYU5SQjhWwmcfDyC/kecNpTvnHjXHlkCyvg3GTaZ5Z7xf7Lw7OTgbA3l6JtGMmXKc8cSjofu8DzwAsmjonCpNqHo66duTycy468/m2KaBelh0uUfu43vJwpR8IUjLCIWtGAVjlcsWZpdaz0HJB4b6hXTdzBlcDBl9LyfD0N5zOth5EApuuA+dmbPuQLQpdirte0K/BQlC1LxXgYCMhi5iV4ytknwOD6vUyGHDDAG9eB4="
  file: 'test.txt'
  on:
    tags: true
